package encription;
import com.jtattoo.plaf.noire.NoireLookAndFeel;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipOutputStream;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;


public class soft extends javax.swing.JFrame {
    private String newentry;
     private String newentryde;
    private String encfile;
    private String decfile;


    /**
     * Creates new form soft
     */
    public soft() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        encpane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtselectfile = new javax.swing.JTextField();
        txtlocation = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        btngenkey = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtgenerate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        pb1 = new javax.swing.JProgressBar();
        encryptlabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        opentf = new javax.swing.JTextField();
        btndecfile = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        savetft = new javax.swing.JTextField();
        btndecloc = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtdeckey = new javax.swing.JTextField();
        btndecrypt = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        decryptlabel = new javax.swing.JLabel();
        compnl = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comselcttft = new javax.swing.JTextField();
        comloctft = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        decompress = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        DECOMSLTTFT = new javax.swing.JTextField();
        DCOMLOCTFT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        toolsjpnl = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        help = new javax.swing.JPanel();
        Btnabt = new javax.swing.JButton();
        btnenc = new javax.swing.JButton();
        btndec = new javax.swing.JButton();
        logo3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txthelp = new javax.swing.JTextPane();
        jSeparator3 = new javax.swing.JSeparator();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("R3 SECURITY SYSTEM");
        setResizable(false);

        encpane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Select");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtselectfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtselectfileActionPerformed(evt);
            }
        });

        jButton4.setText("Encrypt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btngenkey.setText("Generate");
        btngenkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenkeyActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Generate Key");

        txtgenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenerateActionPerformed(evt);
            }
        });

        jLabel2.setText("SELECT FILE  :");

        jLabel4.setText("LOCATION     :");

        jButton9.setBackground(new java.awt.Color(51, 51, 51));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/encription/00000.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        pb1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtgenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtselectfile, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btngenkey)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(encryptlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtselectfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btngenkey, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(encryptlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(16, 16, 16))
        );

        encpane.addTab("ENCRYPTION", jPanel1);

        jLabel6.setText("SELECT FILE  :");

        opentf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opentfActionPerformed(evt);
            }
        });

        btndecfile.setText("SELECT");
        btndecfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecfileActionPerformed(evt);
            }
        });

        jLabel7.setText("LOCATION    :");

        btndecloc.setText("SELECT");
        btndecloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeclocActionPerformed(evt);
            }
        });

        jLabel8.setText("ENTER KEY :");

        txtdeckey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeckeyActionPerformed(evt);
            }
        });

        btndecrypt.setText("DECRYPT");
        btndecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecryptActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/encription/00000.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(584, 584, 584)
                .addComponent(jSeparator2))
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(458, 458, 458))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btndecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(opentf)
                                    .addComponent(savetft, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btndecfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btndecloc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(76, 76, 76))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtdeckey, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(decryptlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel8, txtdeckey});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndecfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opentf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savetft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndecloc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtdeckey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(decryptlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btndecrypt)
                .addContainerGap())
        );

        encpane.addTab("DECRYPTION", jPanel2);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/encription/00000.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("SELECT FILE  :");

        jLabel5.setText("LOCATION     :");

        comselcttft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comselcttftActionPerformed(evt);
            }
        });

        comloctft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comloctftActionPerformed(evt);
            }
        });

        jButton6.setText("Select");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("COMPRESS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton11.setText("Output");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout compnlLayout = new javax.swing.GroupLayout(compnl);
        compnl.setLayout(compnlLayout);
        compnlLayout.setHorizontalGroup(
            compnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(compnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(compnlLayout.createSequentialGroup()
                        .addGroup(compnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comselcttft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(comloctft, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(compnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 634, Short.MAX_VALUE)
        );

        compnlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton6, jButton8});

        compnlLayout.setVerticalGroup(
            compnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compnlLayout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(compnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comselcttft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(compnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comloctft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(33, 33, 33))
        );

        compnlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton6, jButton8});

        encpane.addTab("COMPRESSION", compnl);

        jButton14.setBackground(new java.awt.Color(51, 51, 51));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/encription/00000.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Select");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        DECOMSLTTFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DECOMSLTTFTActionPerformed(evt);
            }
        });

        DCOMLOCTFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DCOMLOCTFTActionPerformed(evt);
            }
        });

        jLabel14.setText("SELECT FILE   :");

        jLabel15.setText("LOCATION      :");

        jButton17.setText("DECOMPRESS");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton13.setText("Output");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout decompressLayout = new javax.swing.GroupLayout(decompress);
        decompress.setLayout(decompressLayout);
        decompressLayout.setHorizontalGroup(
            decompressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 634, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decompressLayout.createSequentialGroup()
                .addGroup(decompressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, decompressLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(decompressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(decompressLayout.createSequentialGroup()
                                .addGroup(decompressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(decompressLayout.createSequentialGroup()
                                .addGroup(decompressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DECOMSLTTFT, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DCOMLOCTFT, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(decompressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(decompressLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton17)))
                .addGap(88, 88, 88))
        );
        decompressLayout.setVerticalGroup(
            decompressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decompressLayout.createSequentialGroup()
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(decompressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DECOMSLTTFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15))
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(decompressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DCOMLOCTFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(jButton17)
                .addGap(25, 25, 25))
        );

        encpane.addTab("DECOMPRESSION", decompress);

        jLabel10.setText("FILE SPLITTER");

        jLabel11.setText("FILE JOINER");

        jButton7.setText("OPEN");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setText("OPEN");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/encription/00000.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolsjpnlLayout = new javax.swing.GroupLayout(toolsjpnl);
        toolsjpnl.setLayout(toolsjpnlLayout);
        toolsjpnlLayout.setHorizontalGroup(
            toolsjpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 634, Short.MAX_VALUE)
            .addGroup(toolsjpnlLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(toolsjpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(toolsjpnlLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addGroup(toolsjpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        toolsjpnlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton10, jButton7});

        toolsjpnlLayout.setVerticalGroup(
            toolsjpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolsjpnlLayout.createSequentialGroup()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addGroup(toolsjpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(toolsjpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        toolsjpnlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton10, jButton7});

        encpane.addTab("     TOOLS   ", toolsjpnl);

        Btnabt.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        Btnabt.setText("About");
        Btnabt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnabtActionPerformed(evt);
            }
        });

        btnenc.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        btnenc.setText("Encryption");
        btnenc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnencActionPerformed(evt);
            }
        });

        btndec.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        btndec.setText("Decryption");
        btndec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecActionPerformed(evt);
            }
        });

        logo3.setBackground(new java.awt.Color(51, 51, 51));
        logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/encription/00000.png"))); // NOI18N
        logo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logo3ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txthelp);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton16.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton16.setText("Compression");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        jButton18.setText("Decompression");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout helpLayout = new javax.swing.GroupLayout(help);
        help.setLayout(helpLayout);
        helpLayout.setHorizontalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btnabt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(helpLayout.createSequentialGroup()
                .addComponent(logo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        helpLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton16, jButton18});

        helpLayout.setVerticalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(Btnabt)
                .addGap(42, 42, 42)
                .addComponent(btnenc)
                .addGap(43, 43, 43)
                .addComponent(btndec)
                .addGap(37, 37, 37)
                .addComponent(jButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton18)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(helpLayout.createSequentialGroup()
                .addComponent(logo3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        encpane.addTab("     HELP      ", help);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(encpane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encpane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opentfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opentfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opentfActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  JFileChooser chooser = new JFileChooser();
    chooser.setCurrentDirectory(new java.io.File("."));
    chooser.setDialogTitle("choosertitle");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    chooser.setAcceptAllFileFilterUsed(false);

    if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        File loc= chooser.getSelectedFile();
        txtlocation.setText( loc.getPath());
     
      
    } else {
      System.out.println("No Selection ");
    }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(jButton1);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            txtselectfile.setText(file.getPath());
            encfile=file.getName();
          
            //This is where a real application would open the file.
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnabtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnabtActionPerformed
txthelp.setText("Secure system is a mini 3rd year project of students Of CSE Branch Of , Knit Sultanpur by"
        + " Ratnesh keshari,Shubhrant Pandey,Raviraj singh. We have Created "
        + "this Software on JDK. The Purpose "
        + "Of This Software is to secure Data"
        + "by Encrypting it & Retrieve Data by"
        + " Decrypting it");        // TODO add your handling code here:
    }//GEN-LAST:event_BtnabtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnencActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnencActionPerformed
       txthelp.setText("This is a Simple process."
                 + "Select The file & location then Generate "
               + "the key (which will be used by the client for Decryption) "
               + "& finally encrypt the data"); // TODO add your handling code here:
    }//GEN-LAST:event_btnencActionPerformed

    private void btndecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndecActionPerformed
       txthelp.setText("This Is a reversible process of encryption"
               + "Select The Encrypted Data and Location"
               + "Then enter the Generated Key"
               + "Then SImply Decrypt it");  
    }//GEN-LAST:event_btndecActionPerformed

    private void btngenkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenkeyActionPerformed
               
                int s= (int) (Math.random()*789459084);
                
              
                String key;
                key=Integer.toHexString(s);
                
                txtgenerate.setText(key);
                        // Generate a AES key
    
    }//GEN-LAST:event_btngenkeyActionPerformed

    private void btndecfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndecfileActionPerformed
final JFileChooser fc = new JFileChooser();

//In response to a button click:
        int returnVal = fc.showOpenDialog(jButton3);
 

        if (returnVal == JFileChooser.APPROVE_OPTION) {
           
            
            File file = fc.getSelectedFile(); 
            
            opentf.setText(file.getPath());
            decfile=file.getName();
          
            //This is where a real application would open the file.
         // TODO add your handling code here:
    }//GEN-LAST:event_btndecfileActionPerformed
    }
    private void btndeclocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeclocActionPerformed
JFileChooser chooser = new JFileChooser();
    chooser.setCurrentDirectory(new java.io.File("."));
    chooser.setDialogTitle("choosertitle");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    chooser.setAcceptAllFileFilterUsed(false);

    if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        File loc= chooser.getSelectedFile();
        savetft.setText( loc.getPath());
     
      
    } else {
      System.out.println("No Selection ");
    }     
    }//GEN-LAST:event_btndeclocActionPerformed

    private void logo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logo3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtselectfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtselectfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtselectfileActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   FileInputStream fis=null;
                FileOutputStream fos=null;
                byte[] buffer =new byte[204800];
                int n=0;
               String strBinarykey = txtgenerate.getText();
                int key = Integer.parseInt(strBinarykey,16);
         
                try
                {
                    fis=new FileInputStream(txtselectfile.getText());
                    fos=new FileOutputStream(txtlocation.getText()+"\\encrypt"+encfile);
                    
                     while((n=fis.read(buffer))!=-1)
                    {
                        for(int i=0;i<n;i++)
                        {
                            buffer[i]+=key;
                        }
                        fos.write(buffer, 0, n);
                        
                              
                    }
                    fos.close();
                    fis.close();
                    pb1.setMinimum(0);
                    pb1.setMaximum(100);
                    pb1.setValue(100);
                    
                }
                catch(Exception e)
                {
                    
                }
                finally
                {
                    try
                    {
                        fis.close();
                        fos.close();
                    }
                    catch(Exception e)
                    {
                                                                     
                    }
                }
                encryptlabel.setText("File has been successfully encrypted:");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btndecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndecryptActionPerformed
 FileInputStream fis=null;
                FileOutputStream fos=null;
                byte[] buffer =new byte[204800];
                int n=0;
                String strBinarykey = txtdeckey.getText();
                int key = Integer.parseInt(strBinarykey,16);
               
                try
                {
                    fis=new FileInputStream(opentf.getText());
                    fos=new FileOutputStream(savetft.getText()+"\\d"+decfile);
            
                     while((n=fis.read(buffer))!=-1)
                    {
                        for(int i=0;i<n;i++)
                        {
                            buffer[i]-=key;
                        }
                        fos.write(buffer, 0, n);
                              
                    }
                    fos.close();
                    fis.close();
                }
                catch(Exception e)
                {
                    
                }
                finally
                {
                    try
                    {
                        fis.close();
                        fos.close();
                    }
                    catch(Exception e)
                    {
                                                                     
                    }
                }
      decryptlabel.setText("file has benn successfully decrypted;");
    }//GEN-LAST:event_btndecryptActionPerformed

    private void txtdeckeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeckeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdeckeyActionPerformed

    private void txtgenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenerateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenerateActionPerformed

    private void comloctftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comloctftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comloctftActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
  FileInputStream inStream = null;
 
        try {
            inStream = new FileInputStream(comselcttft.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
        }
    ZipOutputStream outStream = null;
     
        try {
       outStream =  new ZipOutputStream( new FileOutputStream(comloctft.getText()+".zip"));
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            outStream.putNextEntry(new ZipEntry(newentry));
        } catch (IOException ex) {
            Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
        }

    byte[] buffer = new byte[1024];
    int bytesRead;
        try {
            while ((bytesRead = inStream.read(buffer)) > 0) {
              outStream.write(buffer, 0, bytesRead);
            }
        } catch (IOException ex) {
            Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            outStream.closeEntry();
        } catch (IOException ex) {
            Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            outStream.close();
        } catch (IOException ex) {
            Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            inStream.close();
        } catch (IOException ex) {
            Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
final JFileChooser fc = new JFileChooser();

//In response to a button click:
        int returnVal = fc.showOpenDialog(jButton3);
 

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            
            
            File file = fc.getSelectedFile(); 
            
            comselcttft.setText(file.getPath());
            //comloctft.setText(file.getParent()+"\\compress"+file.getName());
            newentry=file.getName();
          
            //This is where a real application would open the file.
         // TODO add your handling code here:
    } 
                                           
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
new SPLITTER().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
new joinner().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void DECOMSLTTFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DECOMSLTTFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DECOMSLTTFTActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
 JFileChooser fc = new JFileChooser();

//In response to a button click:
        int returnVal = fc.showOpenDialog(jButton3);
 

        if (returnVal == JFileChooser.APPROVE_OPTION) {
           
            
            
            
            File file = fc.getSelectedFile(); 
            newentryde = file.getName();
            
            
           
           
            
            
            DECOMSLTTFT.setText(file.getPath());
            //DCOMLOCTFT.setText(file.getParent()+"\\decompress"+p);
           
        }
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        OutputStream outStream = null;
        try {
            ZipInputStream inStream = null;
            try {
                inStream = new ZipInputStream(new FileInputStream(DECOMSLTTFT.getText()));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
            }
            outStream = new FileOutputStream(DCOMLOCTFT.getText());
            byte[] buffer = new byte[1024];
            int read;
            ZipEntry entry ;
            try {
                if ((entry = inStream.getNextEntry()) != null) {
                    try {
                        while ((read = inStream.read(buffer)) > 0) {
                              try {
                                  outStream.write(buffer, 0, read);
                              } catch (IOException ex) {
                                  Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
                              }
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                outStream.close();
            } catch (IOException ex) {
                Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                inStream.close();     
                // TODO add your handling code here:
            } catch (IOException ex) {
                Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                outStream.close();
            } catch (IOException ex) {
                Logger.getLogger(soft.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
 txthelp.setText("This is a Simple process."
                 + "Select The file"
               + " & Click Compress & it will be compressed"
               + "at the same location where original file is located");       // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
       txthelp.setText("This is a Simple process."
                 + "Select The file"
               + " & Click Decompress & it will be decompressed"
               + "at the same location where compressed file is located");  // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
 JFileChooser chooser = new JFileChooser();
    chooser.setCurrentDirectory(new java.io.File("."));
    chooser.setDialogTitle("choosertitle");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    chooser.setAcceptAllFileFilterUsed(false);

    if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        File loc= chooser.getSelectedFile();
        comloctft.setText( loc.getPath()+"/" + newentry);
     
      
    } else {
      System.out.println("No Selection ");
    }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void DCOMLOCTFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DCOMLOCTFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DCOMLOCTFTActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
JFileChooser chooser = new JFileChooser();
    chooser.setCurrentDirectory(new java.io.File("."));
    chooser.setDialogTitle("choosertitle");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    chooser.setAcceptAllFileFilterUsed(false);
String p="";
int l = newentryde.length();
for(int i =0; i<=l-5; i++)
{
p = p+ newentryde.charAt(i);
}
    if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        File loc= chooser.getSelectedFile();
        DCOMLOCTFT.setText( loc.getPath() +"/"+p);
     
      
    } else {
      System.out.println("No Selection ");
    }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void comselcttftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comselcttftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comselcttftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    try {
           
            LookAndFeel a = new NoireLookAndFeel() ;
            UIManager.setLookAndFeel(a);
           
           
        } catch (Exception e) {
        }        
        
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new soft().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnabt;
    private javax.swing.JTextField DCOMLOCTFT;
    private javax.swing.JTextField DECOMSLTTFT;
    private javax.swing.JButton btndec;
    private javax.swing.JButton btndecfile;
    private javax.swing.JButton btndecloc;
    private javax.swing.JButton btndecrypt;
    private javax.swing.JButton btnenc;
    private javax.swing.JButton btngenkey;
    private javax.swing.JTextField comloctft;
    private javax.swing.JPanel compnl;
    private javax.swing.JTextField comselcttft;
    private javax.swing.JPanel decompress;
    private javax.swing.JLabel decryptlabel;
    private javax.swing.JTabbedPane encpane;
    private javax.swing.JLabel encryptlabel;
    private javax.swing.JPanel help;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    public javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logo3;
    private javax.swing.JTextField opentf;
    public javax.swing.JProgressBar pb1;
    private javax.swing.JTextField savetft;
    private javax.swing.JPanel toolsjpnl;
    private javax.swing.JTextField txtdeckey;
    private javax.swing.JTextField txtgenerate;
    private javax.swing.JTextPane txthelp;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtselectfile;
    // End of variables declaration//GEN-END:variables

    private JComponent jButton1ActionPerformed() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
}
